//****************************************************************
//* lite-manager                                                 *
//* NOTE: do not edit this file as it is automatically generated *
//****************************************************************

#ifndef  __CONFIG_H__
#define  __CONFIG_H__


#define  CONFIG_SGL_PANEL_PIXEL_DEPTH                      16
#define  CONFIG_SGL_EVENT_QUEUE_SIZE                       16
#define  CONFIG_SGL_SYSTICK_MS                             10
#define  CONFIG_SGL_DIRTY_AREA_THRESHOLD                   64
#define  CONFIG_SGL_COLOR16_SWAP                           0   
#define  CONFIG_SGL_ANIMATION                              0
#define  CONFIG_SGL_DEBUG                                  0
#define  CONFIG_SGL_LOG_COLOR                              1
#define  CONFIG_SGL_LOG_LEVEL                              0
#define  CONFIG_SGL_EXTERNAL_PIXMAP                        0  
#define  CONFIG_SGL_OBJ_USE_NAME                           0
#define  CONFIG_SGL_BOOT_LOGO                              0
#define  CONFIG_SGL_BOOT_ANIMATION                         0
#define  CONFIG_SGL_HEAP_ALGO                              lwmem
#define  CONFIG_SGL_HEAP_MEMORY_SIZE                       10240
#define  CONFIG_SGL_FONT_SONG23                            1
#define  CONFIG_SGL_FONT_CONSOLAS14                        0
#define  CONFIG_SGL_FONT_CONSOLAS23                        0
#define  CONFIG_SGL_FONT_CONSOLAS24                        0
#define  CONFIG_SGL_FONT_CONSOLAS32                        0


#endif  //!__CONFIG_H__
