//****************************************************************
//* lite-manager                                                 *
//* NOTE: do not edit this file as it is automatically generated *
//****************************************************************

#ifndef  __CONFIG_H__
#define  __CONFIG_H__


#define    CONFIG_SGL_PANEL_PIXEL_DEPTH       16
#define    CONFIG_SGL_SYSTICK_MS              10
#define    CONFIG_SGL_EVENT_QUEUE_SIZE        16
#define    CONFIG_SGL_DIRTY_AREA_NUM_MAX      16
#define    CONFIG_SGL_ANIMATION               1
#define    CONFIG_SGL_DEBUG                   1
#define    CONFIG_SGL_LOG_COLOR               1
#define    CONFIG_SGL_LOG_LEVEL               0
#define    CONFIG_SGL_OBJ_USE_NAME            1
#define    CONFIG_SGL_FONT_COMPRESSED         1
#define    CONFIG_SGL_BOOT_LOGO               1
#define    CONFIG_SGL_BOOT_ANIMATION          1
#define    CONFIG_SGL_HEAP_ALGO               lwmem
#define    CONFIG_SGL_FL_INDEX_MAX            20
#define    CONFIG_SGL_HEAP_MEMORY_SIZE        10240
#define    CONFIG_SGL_FONT_SONG23             1
#define    CONFIG_SGL_FONT_CONSOLAS14         1
#define    CONFIG_SGL_FONT_CONSOLAS23         1
#define    CONFIG_SGL_FONT_CONSOLAS24         1
#define    CONFIG_SGL_FONT_CONSOLAS32         1
#define    CONFIG_SGL_FONT_CONSOLAS24_COMPRESS     1


#endif /* __SGL_CONFIG_H__ */
